### PR TITLE
Telescope Create

### PR DESCRIPTION
**Pull request by polarmutex**
This PR is to work on adding the ability to create worktrees in the telescope extension

### CODE REVIEW

**Comment by polarmutex** [comment]
have a simplified working example

need to find the best way to input the folder to write the worktree too

**Comment by ThePrimeagen** [comment]
> have a simplified working example
> 
> need to find the best way to input the folder to write the worktree too

vim.fn.prompt?

We could also use plenary's pop up window for input.

**Comment by polarmutex** [comment]
added the prompt, but the window does not start in insert mode even when i command it. I have no clue why

**Comment by ThePrimeagen** [comment]
Let me play with it tonight. I am pretty sure it's just missing an extra schedule.

**Comment by ThePrimeagen** [comment]
I am going to merge this and see what happens.  Hopefully you at least ensured that switching branches still is 100% :)

**Pull request merged**
