### PR TITLE
Add the `update_on_change_command` option

### LINKED ISSUE #33: [Configuration] Make ":Ex path" configurable
It would be great if the user could configure the command which gets executed upon `update_on_change`.
Personally, I used to have `netrw` disabled and instead use [vim-dirvish](https://github.com/justinmk/vim-dirvish). This would be an easy fix if one could specify a setup-option (say e.g. `update_on_change_command`) and a user could exchange `:Ex` with `:Dirvish`. However, once we make this configurable one could even allow any vim-command (or even any lua function) to be given here. Right now, I am thinking that something like `:Telescope git_files` might be even cooler :thinking: 

I am happy to open a PR for this but wanted to get some input first.
- would a simple string command-option be enough?
- or do you think we need a lua function as the configurable option, such that we can also handle `path` being passed into it?
- actually on second though, why do we need to pass `path` to it? Isn't simply `:Ex` enough?

### PR DESCRIPTION
**Pull request by mrossinek**
Closes #33

As proposed there, I really think that this is a useful configuration option. Personally, I am currently using it with `:Telescope git_files` :+1:

### CODE REVIEW

**Comment by mrossinek** [comment]
Hi @ThePrimeagen :slightly_smiling_face: Any update on whether you are willing to include this patch?

**Comment by ThePrimeagen** [comment]
So sorry. In the hospital, will try to resolve this next week!

**Comment by ThePrimeagen** [comment]
@polarmutex if you say this is good I'll merge

**Comment by mrossinek** [comment]
> So sorry. In the hospital, will try to resolve this next week!

No worries! I didn't mean to rush :slightly_smiling_face: Just wanted to check in for an update :+1:

**Comment by polarmutex** [comment]
all seems good to me, thx for your contribution

**Pull request merged**
