### PR TITLE
Make telescope plugin use branch name as path if none is defined. Related to #52

### PR DESCRIPTION
**Pull request by FCO**

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
I assume that this should work.  

Have you tried it out a few times?

**Comment by FCO** [comment]
Yes, I have. Worked every time. Is there no way to write tests to it?

**Comment by ThePrimeagen** [comment]
There are tests, but I am unsure how to test this since it has to do with tele!

**Comment by FCO** [comment]
I just saw the tests folder (sorry I was directly to the code, haven't seen that). I'll try to take a read on that and try to figure out a way of testing it (but if you can't see how I'll probably not find a way as well)

**Pull request merged**
