### PR TITLE
Bug: Clone on windows fails because of :w file

### PR DESCRIPTION
**Pull request by koenverburg**
This will resolve a clone issue on Windows

The error I got on Windows:

image

### CODE REVIEW

**Comment by mrossinek** [comment]
I actually don't think that this file is required at all. It looks like an erroneous `:w:w` Vim command got executed, resulting in this file.
I assume you can change this PR to remove the file entirely, rather than just rename it.

**Comment by ThePrimeagen** [comment]
Lets `rm -rf` that.  Now personally I prefer having the legacy of my hyper saving within a project, but I'll be fine with a delete.

@koenverburg as always.  I am sorry.  Ever since May 12th its been very hard to maintain these repos without huge delay.  Babies make things slow :)

**Comment by koenverburg** [comment]
@ThePrimeagen I removed the file, you can merge the pull request when you have time :)

**Comment by ThePrimeagen** [comment]
@koenverburg I am so sorry I let this slip off my radar!

**Pull request merged**
