### PR TITLE
WIP: telescope support

### PR DESCRIPTION
**Pull request by polarmutex**

### CODE REVIEW

**Comment by polarmutex** [comment]
is it possible to switch back to the non worktree or you suppose to have a worktree for every branch you want?

**Comment by polarmutex** [comment]
switch worktree works on pressing enter, do we want delete and create worktree within telescope?

**Comment by tjdevries** [comment]
Is this project abandonded?

**Comment by ThePrimeagen** [comment]
@polarmutex yes, we want to delete.  Create is hard.  If you are selecting an upstream that exists, then you still need vim.fn.prompt (or whatever its called).

Lets hold off on create and discuss.

**Comment by tjdevries** [comment]
As conni mentioned in chat, you could use the oneshot style finder from telescope if you wanted -- this probably would be easier for you since it handles putting the results in as they come.

For example, git_files is implemented like:

```lua
git.files = function(opts)
  local show_untracked = utils.get_default(opts.show_untracked, true)
  local recurse_submodules = utils.get_default(opts.recurse_submodules, false)
  if show_untracked and recurse_submodules then
    error("Git does not suppurt both --others and --recurse-submodules")
  end

  -- By creating the entry maker after the cwd options,
  -- we ensure the maker uses the cwd options when being created.
  opts.entry_maker = opts.entry_maker or make_entry.gen_from_file(opts)

  pickers.new(opts, {
    prompt_title = 'Git Files',
    finder = finders.new_oneshot_job(
      vim.tbl_flatten( {
        "git", "ls-files", "--exclude-standard", "--cached",
        show_untracked and "--others" or nil,
        recurse_submodules and "--recurse-submodules" or nil
      } ),
      opts
    ),
    previewer = conf.file_previewer(opts),
    sorter = conf.file_sorter(opts),
  }):find()
end
```

**Comment by ThePrimeagen** [comment]
ctrl+d = delete yeah!
enter = switch branch!

create?  perhaps a phone call or a proposed experience!  Its a bit confusing since its 2 separate values :)

**Comment by polarmutex** [comment]
still think we could improve the telescope list display as i just display what "git worktree list" returns, but in its current state seems to work forkme.

well just noticed the bare repo is in the list, it probably needs hidden. but this feature seems close, just need to discuss create

**Comment by ThePrimeagen** [comment]
Hey, can I merge?  This seems exciting!  I really want to use!

**Comment by polarmutex** [comment]
it is good to go as is (at least in my testing) just need to figure out how we want to do to create a worktree

**Comment by ThePrimeagen** [comment]
I'll be using it ASAP!!!! Very excited

**Comment by Conni2461** [comment]
I know this Project is abandonded but its so sad that we never got a `create` for the telescope integration. Maybe someone can continue this project as fork.
I am thinking that person can do something like this:
- insert name in prompt (similar to `builtin.file_browser` touch file)
- `<c-e>` get name, first parameter, over `action_state.get_current_line`
- start `bultin.git_branch` with custom `<CR>` action (and maybe disabling the other actions)
- Take return of that builtin as second parameter

Because of legal issues i am not allowed to give any more input regarding telescope ;)

**Comment by CsarChvz** [comment]
:)

**Pull request merged**
