### PR TITLE
Add confirming of deletions again, and fix force deleting

### PR DESCRIPTION
**Pull request by brandoncc**

### CODE REVIEW

**Comment by brandoncc** [comment]
@polarmutex @ThePrimeagen Can one of you merge this please? I don't seem to have write access.

I fixed deleting by adding a momentary toggle for forced deletions. Pressing `<C-f>` enables forcing for the next deletion. If an unforced deletion fails, a message is shown recommending `<C-f>` if the user wants to force deletion.

**Comment by ThePrimeagen** [comment]
I thought I gave you merge privileges. My fault. I am unable to review it but if you say it's good to go I will trust you.

**Comment by ThePrimeagen** [comment]
@brandoncc @polarmutex 

I'll try to be dedicating 3 hours a week on Tuesdays for open source work. It's difficult to squeeze all these things in.

**Comment by brandoncc** [comment]
Thank you, sir. Merry Christmas to you and your family!

**Pull request merged**
