### PR TITLE
Fix error message when launching vim from the bare repo

### PR DESCRIPTION
**Pull request by martini97**
When launching vim from a the root of a bare repo it would flash an error message:
```
[git-worktree-nvim] [ERROR 20:45:16] .../lua/git-worktree/init.lua:104: Error in determining the git toplevel
```
That would not break the functionality but was annoying.

Btw, I couldn't figure out what you were using for formatting, I guessed stylua with this config:
```toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferDouble"
no_call_parentheses = false
```
I've also moved some git related functionality into a git module, just to better organize myself, hope that's ok.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
this is really good :)  let me review it, but i run into this from time to time.

**Comment by ThePrimeagen** [comment]
also, thanks for the style update.  I haven't done that yet for this repo.

My only thing is columns be set to 80.  Everything else great.

**Comment by martini97** [comment]
Alright, I'll split the changes, but I'm having some issues getting the tests to fail locally, any tips on that?

**Comment by ThePrimeagen** [comment]
> Alright, I'll split the changes, but I'm having some issues getting the tests to fail locally, any tips on that?

I actually have no idea how to this to fail locally if it doesn't.

**Comment by martini97** [comment]
I guess my local config was messing it up, running inside docker solved it

**Comment by martini97** [comment]
Ok, should be working now, I've also changed it to use the `git worktree list`, which should produce an output like:
```
$ git worktree list
/home/martini/personal/git-worktree.nvim.git                      (bare)
/home/martini/personal/git-worktree.nvim.git/fix-bare-root        bb24dfe [fix-bare-root]
/home/martini/personal/git-worktree.nvim.git/foobarbaz-rename-me  9b89f80 [foobarbaz-rename-me]
/home/martini/personal/git-worktree.nvim.git/master               e562d8a [master]
```

**Comment by martini97** [comment]
Hang on, this ain’t going to work on paths containing spaces, I’ll fix that

**Comment by martini97** [comment]
Now it should be ok

**Comment by ThePrimeagen** [comment]
There we go, i'll review today

**Pull request merged**
